### ISSUE TITLE
Support Unpacking RPA in based on Renpy 5.x game

### ISSUE THREAD

**Issue by jwcloverain** [Lattyware/unrpa#44]
## How to reproduce the bug
```
unrpa images.rpa
Extracting files from images.rpa.
Auto-detection of the version for this archived failed—it is likely this archive is a version not supported. Try updating unrpa, or submitting a request for support at https://github.com/Lattyware/unrpa/issues/new?template=new-archive-version.mdHeader: “��~�E�;���R”
You can try using --force to force a specific version rather than relying on auto-detection.
```
```
unrpa images.rpi
Extracting files from images.rpi.
There was an error while trying to extract a file from the archive.
If you wish to try and extract as much from the archive as possible, please use --continue-on-error.
Error Detail: Traceback (most recent call last):
  File "D:\BuildEnv\python\lib\site-packages\unrpa\__init__.py", line 134, in extract_files
    version.postprocess(file_view, output_file)
  File "D:\BuildEnv\python\lib\site-packages\unrpa\versions\version.py", line 24, in postprocess
    for segment in iter(source.read1, b""):
  File "D:\BuildEnv\python\lib\site-packages\unrpa\view.py", line 20, in read1
    return self.base_read(lambda source: source.read1, amount)
  File "D:\BuildEnv\python\lib\site-packages\unrpa\view.py", line 34, in base_read
    return self.base_read(method, amount)
  File "D:\BuildEnv\python\lib\site-packages\unrpa\view.py", line 37, in base_read
    raise Exception("End of archive reached before the file should end.")
Exception: End of archive reached before the file should end.
```
### Files needed to demonstrate the issue
[images.rpa](https://github.com/jwcloverain/unrpabug/blob/master/images.rpa)
[images.rpi](https://github.com/jwcloverain/unrpabug/blob/master/images.rpi)
[loader.py](https://github.com/jwcloverain/unrpabug/blob/master/loader.py)

## How are you running unrpa
 - OS: Windows 10
 - Installation Method pip package
 - Python Version 3.7.9
 - Unrpa Version 2.3.0

**Comment by jwcloverain** [comment]
see this
https://github.com/jwcloverain/DecompileRenpy5/blob/master/unrpa.py
